pbs/risk/urls.py
from .views import (ContextUpdateView,PrescriptionComplexitiesUpdateView,PrescriptionRegistersUpdateView,
        PrescriptionRiskCreateView,PrescriptionMultipleActionCreateView,
        PrescriptionTreatmentDetailView,
        PrescriptionActionUpdateView,PrescriptionActionsUpdateView,PrescriptionPreBurnActionsUpdateView,PrescriptionDayOfBurnActionsUpdateView,PrescriptionPostBurnActionsUpdateView,
        PrescriptionContingencyCreateView,PrescriptionContingencyUpdateView,PrescriptionContingencyListView,
        ContingencyActionCreateView,ContingencyActionUpdateView,ContingencyActionListView,
        ContingencyNotificationCreateView,ContingencyNotificationUpdateView,ContingencyNotificationListView,
        )


app_name = "risk"
urlpatterns = []

urlpatterns.extend(ContextUpdateView.urlpatterns())
urlpatterns.extend(PrescriptionComplexitiesUpdateView.urlpatterns())
urlpatterns.extend(PrescriptionRegistersUpdateView.urlpatterns())
urlpatterns.extend(PrescriptionRiskCreateView.urlpatterns())
urlpatterns.extend(PrescriptionTreatmentDetailView.urlpatterns())
urlpatterns.extend(PrescriptionActionUpdateView.urlpatterns())
urlpatterns.extend(PrescriptionActionsUpdateView.urlpatterns())
urlpatterns.extend(PrescriptionPreBurnActionsUpdateView.urlpatterns())
urlpatterns.extend(PrescriptionDayOfBurnActionsUpdateView.urlpatterns())
urlpatterns.extend(PrescriptionPostBurnActionsUpdateView.urlpatterns())
urlpatterns.extend(PrescriptionMultipleActionCreateView.urlpatterns())

urlpatterns.extend(PrescriptionContingencyCreateView.urlpatterns())
urlpatterns.extend(PrescriptionContingencyUpdateView.urlpatterns())
urlpatterns.extend(PrescriptionContingencyListView.urlpatterns())

urlpatterns.extend(ContingencyActionCreateView.urlpatterns())
urlpatterns.extend(ContingencyActionUpdateView.urlpatterns())
urlpatterns.extend(ContingencyActionListView.urlpatterns())

urlpatterns.extend(ContingencyNotificationCreateView.urlpatterns())
urlpatterns.extend(ContingencyNotificationUpdateView.urlpatterns())
urlpatterns.extend(ContingencyNotificationListView.urlpatterns())

pbs_project/urls.py
from django.urls import include, path
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('docs/', include('django.contrib.admindocs.urls')),
    path('', include('django.contrib.auth.urls'))
]
import pbs.views
import pbs.prescription.urls
import pbs.report.urls
import pbs.risk.urls
import pbs.document.urls
import pbs.stakeholder.urls
import pbs.implementation.urls

from tastypie.api import Api

handler500 = pbs.views.handler500
handler404 = pbs.views.handler404

urlpatterns = urlpatterns + [
    path("admin/",admin.site.urls),
    path("chaining/",include('smart_selects.urls')),
    path("prescription/",include(pbs.prescription.urls,namespace="prescription")),
    path("prescription/",include(pbs.report.urls,namespace="report")),
    path("risk/",include(pbs.risk.urls,namespace="risk")),
    path("document/",include(pbs.document.urls,namespace="document")),
    path("stakeholder/",include(pbs.stakeholder.urls,namespace="stakeholder")),
    path("implementation/",include(pbs.implementation.urls,namespace="implementation"))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
for p in urlpatterns:
    print(p)

swingers/conf/project_template/project_name/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'dec_template.views.home', name='home'),
    # url(r'^dec_template/', include('dec_template.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
)

pbs/document/models.py
import logging
import datetime
import os
from functools import reduce

from smart_selects.db_fields import ChainedForeignKey

from django.contrib.gis.db import models
from django.utils import timezone
from django.db.models import Q,Max
from django.dispatch import receiver
from django.db.models.signals import post_delete

from dpaw_utils.models import (AuditMixin,ModelDictMixin)

from pbs.document.fields import ContentTypeRestrictedFileField
from pbs.document.utils import get_dimensions
from pbs.prescription.models import Prescription

logger = logging.getLogger(__name__)
# Create your models here.

def content_file_name(self, filename):
    if filename.rsplit('.')[-1] == "zip":
        extension = "zip"
    else:
        extension = "pdf"
    return "uploads/{0}/{0}_{1}_{2}_{3}.{4}".format(
        str(self.prescription.season).strip().replace("/", "_"),
        self.prescription.burn_id,
        self.descriptor.strip().replace(" ", "_"),
        timezone.localtime(self.document_created).isoformat(
        ).rsplit(".")[0].replace(":", "")[:-7],
        extension)


class DocumentCategory(models.Model):
    name = models.CharField(max_length=200)
    order = models.PositiveSmallIntegerField(default=0)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Document Category"
        verbose_name_plural = "Document Categories"
        ordering = ['name']

documentcategory_list = [(o.id,o.name) for o in DocumentCategory.objects.all().order_by('name')]

class CategoryManager(models.Manager):
    def _query_by_names(self, *names):
        return reduce(lambda x, y: x | y,
                      (Q(name__iexact=name) for name in names),
                      Q())

    def not_tag_names(self, *names):
        return self.get_queryset().exclude(self._query_by_names(*names))

    def tag_names(self, *names):
        return self.get_queryset().filter(self._query_by_names(*names))


class DocumentTag(models.Model):
    name = models.CharField(verbose_name="Document Tag", max_length=200)
    category = models.ForeignKey(DocumentCategory, on_delete=models.PROTECT)

    objects = CategoryManager()

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']
        base_manager_name = "objects"

class TagManager(models.Manager):
    def _query_by_names(self, *names):
        return reduce(lambda x, y: x | y,
                      (Q(tag__name__iexact=name) for name in names),
                      Q())

    def not_tag_names(self, *names):
        return self.get_queryset().exclude(self._query_by_names(*names))

    def tag_names(self, *names):
        return self.get_queryset().filter(self._query_by_names(*names))

    def __getattr__(self, name):
        if name[:4] == "tag_":
            qs = self.get_queryset().filter(
                tag__name__iexact=name[4:].replace("_", " "))
            qs.modified = qs.aggregate(Max('modified'))["modified__max"]
            return qs
        else:
            return super(TagManager, self).__getattr__(name)

    def printable(self):
        """
        Return the set of printable documents. This removes any zip files from
        the set of documents.
        """
        qs = self.get_queryset()
        return filter(lambda x: x.filename.endswith('.pdf'), qs)


class Document(ModelDictMixin,AuditMixin):
    prescription = models.ForeignKey(
        Prescription, null=True,
        help_text="Prescription that this document belongs to", on_delete=models.PROTECT)
    category = models.ForeignKey(DocumentCategory, related_name="documents", on_delete=models.PROTECT)
    tag = ChainedForeignKey(DocumentTag, chained_field="category",chained_model_field="category",auto_choose=True,show_all=False,sort=True,verbose_name="Descriptor", on_delete=models.PROTECT)
    custom_tag = models.CharField(
        max_length=64, blank=True, verbose_name="Custom Descriptor")
    document = ContentTypeRestrictedFileField(
        upload_to=content_file_name, max_length=200,
        content_types=['application/pdf', 'image/tiff', 'image/tif',
                       'image/jpeg', 'image/jpg', 'image/gif', 'image/png',
                       'application/zip', 'application/x-zip-compressed'],
        help_text='Acceptable file types: pdf, tiff, jpg, gif, png, zip')

    document_created = models.DateTimeField(
        verbose_name="Date Document Created", default=timezone.now, editable=True, null=True, blank=True)

    document_archived = models.BooleanField(default=False, verbose_name="Archived Document")

    objects = TagManager()

    @property
    def descriptor(self):
        if self.custom_tag:
            return "Other ({0})".format(self.custom_tag)
        else:
            return self.tag.name

    @property
    def dimensions(self):
        return get_dimensions(self.document.path)

    @property
    def filename(self):
        try:
            return os.path.basename(self.document.path)
        except:
            return None

    @property
    def exists(self):
        """
        Check if file exists on the file system
        """
        try:
            return os.path.exists(self.document.file.name)
        except:
            return False


    @property
    def is_zipped(self):
        return self.filename.endswith('.zip')

    def clean(self):
        if not self.pk:
            self.category = self.tag.category

    def save(self, *args, **kwargs):
        super(Document, self).save(*args, **kwargs)
        # confirm that file is written to filesystem, if not remove the record
        if not self.exists:
            fname = self.document.name
            Document.objects.get(id=self.id).delete()
            raise Exception('ERROR: File not created on filesystem {}'.format(fname))
        return

    def __str__(self):
        return "{0} - {1}".format(self.prescription, self.document.name)

    class Meta:
        base_manager_name = "objects"
        ordering = ['tag', 'document']
        permissions = (
            ("archive_document", "Can archive documents")
        ,)

class DocumentListener(object):
    @staticmethod
    @receiver(post_delete, sender=Document)
    def delete_document(sender, instance, **kwargs):
        if instance.document:
            instance.document.delete(False)

pbs/risk/views/complexity.py
from django.urls import path 
from django import urls

from pbs.prescription.models import (Prescription,)
from pbs.prescription.forms import (PrescriptionMaximumDraftRiskForm,)
from pbs.risk.models import (Complexity,factorlist)
from pbs.risk.forms import (ComplexityListUpdateForm,ComplexityListForm,ComplexityFilterForm)
from pbs.risk.filters import (ComplexityFilter,)
from dpaw_utils import views
import pbs.forms

class PrescriptionComplexitiesUpdateView(pbs.forms.GetActionMixin,views.OneToManyListUpdateView):
    title = "Prescribed Burn Complexity Analysis Summary"
    pmodel = Prescription
    model = Complexity
    filter_class = ComplexityFilter
    filterform_class = ComplexityFilterForm
    pform_class = PrescriptionMaximumDraftRiskForm
    listform_class = ComplexityListUpdateForm
    context_pform_name = "prescriptionform"
    context_pobject_name = "prescription"
    one_to_many_field_name = "prescription"
    urlpattern = "prescription/<int:ppk>/complexity/"
    urlname = "prescription_complexity_changelist"
    filtertool = False


    @property
    def deleteconfirm_url(self):
        return urls.reverse("risk:prescription_complexities_delete",args=(self.pobject.id,))

    @classmethod
    def _get_extra_urlpatterns(cls):
        model_name = cls.model.__name__.lower()
        return [
            path('prescription/<int:ppk>/complexity/<int:pk>/deleteconfirm', cls.as_view(),{"action":"deleteconfirm"},name='prescription_complexity_delete_confirm'),
            path('prescription/<int:ppk>/complexities/delete', cls.as_view(),{"action":"deleteconfirmed"},name='prescription_complexities_delete'),
        ]

    def _get_success_url(self):
        return urls.reverse("risk:prescription_complexity_changelist",args=(self.pobject.id,))

    def get_listform_class(self):
        if self.action == 'deleteconfirm':
            return ComplexityListForm
        else:
            return super().get_listform_class()

    def update_context_data(self,context):
        super().update_context_data(context)
        context["factorlist"] = factorlist

pbs/risk/views/contingency.py
from django.urls import path 
from django import urls

from pbs.prescription.models import (Prescription,)
from pbs.risk.models import (Contingency,)
from pbs.risk.forms import (ContingencyCreateForm,ContingencyUpdateForm,ActionMigratedContingencyUpdateForm,NotificationMigratedContingencyUpdateForm,UnmigratedContingencyUpdateForm,ContingencyListForm,ContingencyDeleteListForm)
from dpaw_utils import views

import pbs.forms

class PrescriptionContingencyCreateView(pbs.forms.GetActionMixin,views.OneToManyCreateView):
    title = "Add Contingency Plan"
    pmodel = Prescription
    model = Contingency
    form_class = ContingencyCreateForm
    context_pobject_name = "prescription"
    one_to_many_field_name = "prescription"
    urlpattern = "prescription/<int:ppk>/contingency/add/"
    urlname = "prescription_contingency_create"
    template_name_suffix = "_create"

    def _get_success_url(self):
        return urls.reverse("risk:prescription_contingency_list",args=(self.pobject.id,))

class PrescriptionContingencyUpdateView(pbs.forms.GetActionMixin,views.OneToManyUpdateView):
    title = "Change Contingency Plan"
    pmodel = Prescription
    model = Contingency
    form_class = ContingencyUpdateForm
    context_pobject_name = "prescription"
    one_to_many_field_name = "prescription"
    urlpattern = "prescription/<int:ppk>/contingency/<int:pk>/"
    urlname = "prescription_contingency_update"
    template_name_suffix = "_update"

    def get_form_class(self):
        if (self.object.actions_migrated and not self.object.action) and \
            (self.object.notifications_migrated and not self.object.notify_name and not self.object.location and not self.object.organisation and not self.object.contact_number):
            return ContingencyUpdateForm
        elif self.object.actions_migrated and not self.object.action:
            return ActionMigratedContingencyUpdateForm
        elif self.object.notifications_migrated and not self.object.notify_name and not self.object.location and not self.object.organisation and not self.object.contact_number:
            return NotificationMigratedContingencyUpdateForm
        else:
            return UnmigratedContingencyUpdateForm

    def _get_success_url(self):
        return urls.reverse("risk:prescription_contingency_list",args=(self.pobject.id,))


class PrescriptionContingencyListView(pbs.forms.GetActionMixin,views.OneToManyListView):
    title = "Contingency Plan"
    pmodel = Prescription
    model = Contingency
    listform_class = ContingencyListForm
    context_pobject_name = "prescription"
    one_to_many_field_name = "prescription"
    urlpattern = "prescription/<int:ppk>/contingency/"
    urlname = "prescription_contingency_list"
    template_name_suffix = "_list"
    default_order = ("description","id")

    def _get_success_url(self):
        return urls.reverse("risk:prescription_contingency_list",args=(self.pobject.id,))

    @property
    def deleteconfirm_url(self):
        return urls.reverse("risk:prescription_contingencys_delete",args=(self.pobject.id,))

    def get_listform_class(self):
        if self.action == "deleteconfirm":
            return ContingencyDeleteListForm
        else:
            return ContingencyListForm

    @classmethod
    def _get_extra_urlpatterns(cls):
        model_name = cls.model.__name__.lower()
        return [
            path('prescription/<int:ppk>/contingency/<int:pk>/deleteconfirm', cls.as_view(),{"action":"deleteconfirm"},name='prescription_contingency_delete_confirm'),
            path('prescription/<int:ppk>/contingencys/delete', cls.as_view(),{"action":"deleteconfirmed"},name='prescription_contingencys_delete'),
        ]


    """
    def post(self,*args,**kwargs):
        import ipdb;ipdb.set_trace()
        return super().post(*args,**kwargs)
    """

pbs/risk/views/risk.py
from django.urls import path 
from django import urls
from django.db import transaction

from pbs.prescription.models import (Prescription,)
from pbs.risk.models import (Action,Risk)
from pbs.risk.forms import (CustomRiskCreateForm)
from dpaw_utils import views
import pbs.forms

class PrescriptionRiskCreateView(pbs.forms.GetActionMixin,views.OneToManyCreateView):
    title = "Add Potential Sources of Risk"
    pmodel = Prescription
    model = Risk
    form_class = CustomRiskCreateForm
    context_pobject_name = "prescription"
    one_to_many_field_name = "prescription"
    urlpattern = "prescription/<int:ppk>/risk/"
    urlname = "prescription_risk_create"
    template_name_suffix = "_create"

    def _get_success_url(self):
        return urls.reverse("risk:prescription_action_changelist",args=(self.pobject.id,))

    def form_valid(self,form):
        with transaction.atomic():
            result = super().form_valid(form)
            Action(risk = form.instance,relevant=True,index = 1,total = 1).save()
            return result
        

templates/risk/action_dayofburn_changelist.html
{% extends "../changelist.html" %}
{% load i18n %}
{% load pbs_utils %}

{% block breadcrumbs %}
<ul class="breadcrumb">
  <li><a href="{% url 'prescription:prescription_list' %}">{% trans 'Regional Overview' %}</a> <span class="divider">/</span></li>
  <li><a href="{% url 'prescription:prescription_home' prescription.id %}">{{ prescription.burn_id }}</a> <span class="divider">/</span></li>
  <li><a href="{% url 'report:prescription_day_state_update' prescription.id %}">Part B</a> <span class="divider">/</span></li>
  <li>Section B1 &#x2010; Pre-burn Actions</li>
</ul>
{% endblock %}

{% block pretitle %}
<ul class="nav nav-tabs" style="margin-bottom:2px">
    <li><a href="{% url 'risk:context_update' prescription.id %}"><i class="icon-legal"></i> Risk management context statement</a></li>
    <li><a href="{% url 'stakeholder:criticalstakeholder_changelist' prescription.id  %}"><i class="icon-user"></i> Critical stakeholders</a></li>
    <li class="active"><a href="{% url 'risk:prescription_action_changelist' prescription.id %}"><i class="icon-legal"></i> Actions</a></li>
    <li><a href="{% url 'risk:prescription_register_changelist' prescription.id %}"><i class="icon-warning-sign"></i> Risk Register</a></li>
</ul>
<ul id="actionnav" class="nav nav-pills">
    <li><a href="{% url 'risk:prescription_action_changelist' prescription.id %}"><i class="icon-list-ol"></i>Plan actions</a></li>
    <li><a href="{% url 'risk:prescription_preburn_action_changelist' prescription.id %}"><i class="icon-tasks"></i>Pre-burn actions</a></li>
    <li class="active"><a href="{% url 'risk:prescription_dayofburn_action_changelist' prescription.id %}"><i class="icon-legal"></i>Day of burn actions</a></li>
    <li><a href="{% url 'risk:prescription_postburn_action_changelist' prescription.id %}"><i class="icon-warning-sign"></i>Post-burn actions</a></li>
</ul>
{% endblock %}

{% block content_title %}
<div class="row">
    <div class="span12" >
        <h1>Treatments</h1>
        <div class="alert alert-info">
            <strong>Note:</strong> Treatments for this section have been identified in the risk register.
        </div>

        {% include "includes/objectlist.html" with includedlistform=treatmentlistform %}
    </div>
</div>

<div class="row">
    <div class="span12" >
	<h1>Actions Report
           <a href="{% url 'document:prescription_taggeddocument_add' prescription.id 184 %}?nexturl={% url 'risk:prescription_dayofburn_action_changelist' prescription.id %}" class="pull-right btn btn-info btn-small"><b><i class="icon-plus"></i> Upload Day of Burn Actions List</b></a>
	</h1>
	<h5><a class="btn btn-small btn-info" href=""><i class="icon-download-alt"></i> Download the Day of Burn Actions List template</a></h5>
        {% include "document/includes/document_list.html" with document_type="Day of Burn Actoions List" %}
        <h1>{{ title }}
            <a href="{% url 'risk:prescription_risk_create' prescription.id %}" class="pull-right btn btn-small btn-info"><i class="icon-plus"></i> Add source of risk</a>
        </h1>
    </div>
</div>
{% endblock %}

{% block list_content %}
    <table id="{{listform.model_name_lower}}_result_list" class="table table-striped table-condensed table-hober table-fixed-header">
        <thead>
            <tr>
                {% for field in listform.boundfields %}
                {% if field.name != 'factor' %}
                {% call_method field "html_header" "<th{attrs}><div class=\"text\"> {label}</div></th>"%}
                {% endif %}
                {% endfor %}
            </tr>
        </thead>
        <tbody>
            {% for form in listform %}
            {% if category != form.instance.risk.category %}
            <tr>
                <td colspan="{{listform.boundfieldlength}}">{{form.risk__category}}</td>
            </tr>
            {% setvar form.instance.risk.category as category %}
            {% endif %}
            <tr> 
                {% for field in form.boundfields %}
                    {% if field.name == 'sub_factor' %}
                    {% call_method field "html" "<td{attrs}><span style='padding-left:20px'>{widget}</span></td>"%}
                    {% elif field.name != 'factor'%}
                    {% call_method field "html" "<td{attrs}>{widget}</td>"%}
                    {% endif %}
                {% endfor %}
            </tr>
            {% endfor %}

        </tbody>
    </table>
{% endblock %}

templates/risk/action_deleteconfirm.html
{% extends "../deleteconfirm.html" %}
{% load i18n %}
{% load admin_urls %}

{% block breadcrumbs %}
<ul class="breadcrumb">
  <li><a href="{% url 'prescription:prescription_list' %}">{% trans 'Regional Overview' %}</a> <span class="divider">/</span></li>
  <li><a href="{% url 'prescription:prescription_home' prescription.id %}">{{ prescription.burn_id }}</a> <span class="divider">/</span></li>
  <li><a href="{% url 'report:prescription_day_state_update' prescription.id %}">Part B</a> <span class="divider">/</span></li>
  <li><a href="{% url 'risk:prescription_action_changelist' prescription.id %}">Section B1 &#x2010; Plan Actions</a> <span class="divider">/</span></li>
  {% if listform|length == 1 %}
  <li>{{listform.first.instance.risk_name}}<span class="divider">/</span></li>
  {% endif %}
  <li>{% trans 'Delete' %}</li>
</ul>
{% endblock %}

templates/risk/action_multiple_add.html
{% extends "../change_form.html" %}
{% load i18n %}
{% load pbs_utils %}

{% block breadcrumbs %}
<ul class="breadcrumb">
  <li><a href="{% url 'prescription:prescription_list' %}">{% trans 'Regional Overview' %}</a> <span class="divider">/</span></li>
  <li><a href="{% url 'prescription:prescription_home' prescription.id %}">{{ prescription.burn_id }}</a> <span class="divider">/</span></li>
  <li><a href="{% url 'report:prescription_day_state_update' prescription.id %}">Part B</a> <span class="divider">/</span></li>
  <li><a href="{% url 'risk:prescription_action_changelist' prescription.id %}">Section B1 &#x2010; Plan Actions</a> <span class="divider">/</span></li>
  <li>Add Plan Action</li>
</ul>

{% endblock %}

templates/risk/action_postburn_changelist.html
{% extends "../changelist.html" %}
{% load i18n %}
{% load pbs_utils %}

{% block breadcrumbs %}
<ul class="breadcrumb">
  <li><a href="{% url 'prescription:prescription_list' %}">{% trans 'Regional Overview' %}</a> <span class="divider">/</span></li>
  <li><a href="{% url 'prescription:prescription_home' prescription.id %}">{{ prescription.burn_id }}</a> <span class="divider">/</span></li>
  <li><a href="{% url 'report:prescription_day_state_update' prescription.id %}">Part B</a> <span class="divider">/</span></li>
  <li>Section B1 &#x2010; Pre-burn Actions</li>
</ul>
{% endblock %}

{% block pretitle %}
<ul class="nav nav-tabs" style="margin-bottom:2px">
    <li><a href="{% url 'risk:context_update' prescription.id %}"><i class="icon-legal"></i> Risk management context statement</a></li>
    <li><a href="{% url 'stakeholder:criticalstakeholder_changelist' prescription.id  %}"><i class="icon-user"></i> Critical stakeholders</a></li>
    <li class="active"><a href="{% url 'risk:prescription_action_changelist' prescription.id %}"><i class="icon-legal"></i> Actions</a></li>
    <li><a href="{% url 'risk:prescription_register_changelist' prescription.id %}"><i class="icon-warning-sign"></i> Risk Register</a></li>
</ul>
<ul id="actionnav" class="nav nav-pills">
    <li><a href="{% url 'risk:prescription_action_changelist' prescription.id %}"><i class="icon-list-ol"></i>Plan actions</a></li>
    <li><a href="{% url 'risk:prescription_preburn_action_changelist' prescription.id %}"><i class="icon-tasks"></i>Pre-burn actions</a></li>
    <li><a href="{% url 'risk:prescription_dayofburn_action_changelist' prescription.id %}"><i class="icon-legal"></i>Day of burn actions</a></li>
    <li class="active"><a href="{% url 'risk:prescription_postburn_action_changelist' prescription.id %}"><i class="icon-warning-sign"></i>Post-burn actions</a></li>
</ul>
{% endblock %}

{% block content_title %}
<div class="row">
    <div class="span12" >
	<h1>Actions Report
           <a href="{% url 'document:prescription_taggeddocument_add' prescription.id 189 %}?nexturl={% url 'risk:prescription_postburn_action_changelist' prescription.id %}" class="pull-right btn btn-info btn-small"><b><i class="icon-plus"></i> Upload Post Burn Actions List</b></a>
	</h1>
	<h5><a class="btn btn-small btn-info" href=""><i class="icon-download-alt"></i> Download the Pre Burn Actions List template</a></h5>
        {% include "document/includes/document_list.html" with document_type="Post Burn Actoions List" %}
        <h1>{{ title }}
            <a href="{% url 'risk:prescription_risk_create' prescription.id %}" class="pull-right btn btn-small btn-info"><i class="icon-plus"></i> Add source of risk</a>
        </h1>
    </div>
</div>
{% endblock %}

{% block list_content %}
    <table id="{{listform.model_name_lower}}_result_list" class="table table-striped table-condensed table-hober table-fixed-header">
        <thead>
            <tr>
                {% for field in listform.boundfields %}
                {% if field.name != 'factor' %}
                {% call_method field "html_header" "<th{attrs}><div class=\"text\"> {label}</div></th>"%}
                {% endif %}
                {% endfor %}
            </tr>
        </thead>
        <tbody>
            {% for form in listform %}
            {% if category != form.instance.risk.category %}
            <tr>
                <td colspan="{{listform.boundfieldlength}}">{{form.risk__category}}</td>
            </tr>
            {% setvar form.instance.risk.category as category %}
            {% endif %}
            <tr> 
                {% for field in form.boundfields %}
                    {% if field.name == 'sub_factor' %}
                    {% call_method field "html" "<td{attrs}><span style='padding-left:20px'>{widget}</span></td>"%}
                    {% elif field.name != 'factor'%}
                    {% call_method field "html" "<td{attrs}>{widget}</td>"%}
                    {% endif %}
                {% endfor %}
            </tr>
            {% endfor %}

        </tbody>
    </table>
{% endblock %}

templates/risk/contingency_list.html
{% extends "../list.html" %}
{% load i18n %}

{% block breadcrumbs %}
<ul class="breadcrumb">
  <li><a href="{% url 'prescription:prescription_list' %}">{% trans 'Regional Overview' %}</a> <span class="divider">/</span></li>
  <li><a href="{% url 'prescription:prescription_home' prescription.id %}">{{prescription.burn_id}}</a> <span class="divider">/</span></li>
  <li><a href="% url 'report:prescription_day_state_update' prescription.id %}">Part B</a> <span class="divider">/</span></li>
  <li>Section B6 &#x2010;  Contingency Plan</li>
</ul>
{% endblock %}

{% block content_title %}
<h1>{{title}}
    <div class="pull-right">
        <a class="btn btn-small btn-info" href="{% url 'risk:prescription_contingency_create' prescription.id %}">
          <i class="icon-plus icon-white"></i>
          Create Contingency Plan
        </a>
    </div>
</h1>
{% endblock %}