pbs/implementation/urls.py
from .views import (PrescriptionOperationalOverviewUpdateView,
        PrescriptionRoadSegmentListUpdateView,
        PrescriptionTrailSegmentListUpdateView,
        PrescriptionBurningPrescriptionCreateView,PrescriptionBurningPrescriptionUpdateView,PrescriptionBurningPrescriptionListView,
        PrescriptionEdgingPlanCreateView,PrescriptionEdgingPlanUpdateView,PrescriptionEdgingPlanListView,
        PrescriptionExclusionAreaListUpdateView,
        PrescriptionLightingSequenceCreateView,PrescriptionLightingSequenceUpdateView,PrescriptionLightingSequenceListView,
        )


app_name = "implementation"
urlpatterns = []

urlpatterns.extend(PrescriptionOperationalOverviewUpdateView.urlpatterns())
urlpatterns.extend(PrescriptionRoadSegmentListUpdateView.urlpatterns())
urlpatterns.extend(PrescriptionTrailSegmentListUpdateView.urlpatterns())

urlpatterns.extend(PrescriptionBurningPrescriptionCreateView.urlpatterns())
urlpatterns.extend(PrescriptionBurningPrescriptionUpdateView.urlpatterns())
urlpatterns.extend(PrescriptionBurningPrescriptionListView.urlpatterns())

urlpatterns.extend(PrescriptionEdgingPlanCreateView.urlpatterns())
urlpatterns.extend(PrescriptionEdgingPlanUpdateView.urlpatterns())
urlpatterns.extend(PrescriptionEdgingPlanListView.urlpatterns())

urlpatterns.extend(PrescriptionExclusionAreaListUpdateView.urlpatterns())

urlpatterns.extend(PrescriptionLightingSequenceCreateView.urlpatterns())
urlpatterns.extend(PrescriptionLightingSequenceUpdateView.urlpatterns())
urlpatterns.extend(PrescriptionLightingSequenceListView.urlpatterns())

pbs_project/urls.py
from django.urls import include, path
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('docs/', include('django.contrib.admindocs.urls')),
    path('', include('django.contrib.auth.urls'))
]
import pbs.views
import pbs.prescription.urls
import pbs.report.urls
import pbs.risk.urls
import pbs.document.urls
import pbs.stakeholder.urls
import pbs.implementation.urls

from tastypie.api import Api

handler500 = pbs.views.handler500
handler404 = pbs.views.handler404

urlpatterns = urlpatterns + [
    path("admin/",admin.site.urls),
    path("chaining/",include('smart_selects.urls')),
    path("prescription/",include(pbs.prescription.urls,namespace="prescription")),
    path("prescription/",include(pbs.report.urls,namespace="report")),
    path("risk/",include(pbs.risk.urls,namespace="risk")),
    path("document/",include(pbs.document.urls,namespace="document")),
    path("stakeholder/",include(pbs.stakeholder.urls,namespace="stakeholder")),
    path("implementation/",include(pbs.implementation.urls,namespace="implementation"))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
for p in urlpatterns:
    print(p)

swingers/conf/project_template/project_name/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'dec_template.views.home', name='home'),
    # url(r'^dec_template/', include('dec_template.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
)

pbs/implementation/forms/operationaloverview.py
from pbs.forms import (BUTTON_ACTIONS,OPTION_ACTIONS)
from pbs.implementation.models import (OperationalOverview,)

from dpaw_utils import forms

class OperationalOverviewCleanMixin(object):
    pass

class OperationalOverviewConfigMixin(object):
    class Meta:
        field_classes_config = {
            "__default__":forms.fields.CharField,
            "overview":forms.fields.OverrideFieldFactory(OperationalOverview,"overview",field_params={"required":True}),
        }
        labels = {
            "delete":"",
        }
        widgets_config = {
            "__default__.view":forms.widgets.TextDisplay(),
            "__default__.edit":forms.widgets.TextInput(),
            "overview.edit":forms.widgets.Textarea(attrs={"class":"vTextField"}),
        }

class OperationalOverviewBaseForm(OperationalOverviewCleanMixin,OperationalOverviewConfigMixin,forms.ModelForm):
    def set_parent_instance(self,parent_instance):
        self.instance.prescription = parent_instance

    class Meta:
        pass

class OperationalOverviewUpdateForm(OperationalOverviewBaseForm):
    all_buttons = [
        BUTTON_ACTIONS["save"],
    ]
    class Meta:
        model = OperationalOverview
        all_fields = ("overview",)
        editable_fields = ("overview",)

pbs/implementation/views/burningprescription.py
from django.urls import path 
from django import urls

from pbs.prescription.models import (Prescription,)
from pbs.risk.models import (Treatment,)
from pbs.implementation.models import (BurningPrescription,)
from pbs.implementation.forms import (BurningPrescriptionCreateForm,BurningPrescriptionUpdateForm,BurningPrescriptionListForm,)
from pbs.risk.forms import (TreatmentListForm,)
from dpaw_utils import views

import pbs.forms

class PrescriptionBurningPrescriptionCreateView(pbs.forms.GetActionMixin,views.OneToManyCreateView):
    title = "Add Burning Prescription"
    pmodel = Prescription
    model = BurningPrescription
    form_class = BurningPrescriptionCreateForm
    context_pobject_name = "prescription"
    one_to_many_field_name = "prescription"
    urlpattern = "prescription/<int:ppk>/burningprescription/add/"
    urlname = "prescription_burningprescription_create"
    template_name_suffix = "_create"

    def _get_success_url(self):
        return urls.reverse("implementation:prescription_burningprescription_list",args=(self.pobject.id,))

class PrescriptionBurningPrescriptionUpdateView(pbs.forms.GetActionMixin,views.OneToManyUpdateView):
    title = "Change Burning Prescription"
    pmodel = Prescription
    model = BurningPrescription
    form_class = BurningPrescriptionUpdateForm
    context_pobject_name = "prescription"
    one_to_many_field_name = "prescription"
    urlpattern = "prescription/<int:ppk>/burningprescription/<int:pk>/"
    urlname = "prescription_burningprescription_update"
    template_name_suffix = "_update"

    def _get_success_url(self):
        return urls.reverse("implementation:prescription_burningprescription_list",args=(self.pobject.id,))


class PrescriptionBurningPrescriptionListView(pbs.forms.GetActionMixin,views.OneToManyListView):
    title = "Burning Prescriptions"
    pmodel = Prescription
    model = BurningPrescription
    listform_class = BurningPrescriptionListForm
    context_pobject_name = "prescription"
    one_to_many_field_name = "prescription"
    urlpattern = "prescription/<int:ppk>/burningprescription/"
    urlname = "prescription_burningprescription_list"
    template_name_suffix = "_list"
    default_order = ("fuel_type__name","id")

    def get_mediaforms(self):
        return (self.get_listform_class(),TreatmentListForm)

    def _get_success_url(self):
        return urls.reverse("implementation:prescription_burningprescription_list",args=(self.pobject.id,))

    @property
    def deleteconfirm_url(self):
        return urls.reverse("implementation:prescription_burningprescriptions_delete",args=(self.pobject.id,))

    @classmethod
    def _get_extra_urlpatterns(cls):
        model_name = cls.model.__name__.lower()
        return [
            path('prescription/<int:ppk>/burningprescription/<int:pk>/deleteconfirm', cls.as_view(),{"action":"deleteconfirm"},name='prescription_burningprescription_delete_confirm'),
            path('prescription/<int:ppk>/burningprescriptions/delete', cls.as_view(),{"action":"deleteconfirmed"},name='prescription_burningprescriptions_delete'),
        ]


    """
    def post(self,*args,**kwargs):
        import ipdb;ipdb.set_trace()
        return super().post(*args,**kwargs)
    """

    def update_context_data(self,context):
        super().update_context_data(context)
        context["treatmentlistform"] = TreatmentListForm(instance_list=Treatment.objects.filter(register__prescription = self.pobject),request=self.request,requesturl = self.requesturl)
        context["documents_165"] = self.pobject.document_set.filter(tag__id=165)
        context["documents_167"] = self.pobject.document_set.filter(tag__id=167)

pbs/implementation/views/edgingplan.py
from django.urls import path 
from django import urls

from pbs.prescription.models import (Prescription,)
from pbs.risk.models import (Treatment,)
from pbs.implementation.models import (EdgingPlan,)
from pbs.implementation.forms import (EdgingPlanCreateForm,EdgingPlanUpdateForm,EdgingPlanListForm,)
from pbs.risk.forms import (TreatmentListForm,)
from dpaw_utils import views

import pbs.forms

class PrescriptionEdgingPlanCreateView(pbs.forms.GetActionMixin,views.OneToManyCreateView):
    title = "Add Edging Plan"
    pmodel = Prescription
    model = EdgingPlan
    form_class = EdgingPlanCreateForm
    context_pobject_name = "prescription"
    one_to_many_field_name = "prescription"
    urlpattern = "prescription/<int:ppk>/edgingplan/add/"
    urlname = "prescription_edgingplan_create"
    template_name_suffix = "_create"

    def _get_success_url(self):
        return urls.reverse("implementation:prescription_edgingplan_list",args=(self.pobject.id,))

class PrescriptionEdgingPlanUpdateView(pbs.forms.GetActionMixin,views.OneToManyUpdateView):
    title = "Change Edging Plan"
    pmodel = Prescription
    model = EdgingPlan
    form_class = EdgingPlanUpdateForm
    context_pobject_name = "prescription"
    one_to_many_field_name = "prescription"
    urlpattern = "prescription/<int:ppk>/edgingplan/<int:pk>/"
    urlname = "prescription_edgingplan_update"
    template_name_suffix = "_update"

    def _get_success_url(self):
        return urls.reverse("implementation:prescription_edgingplan_list",args=(self.pobject.id,))


class PrescriptionEdgingPlanListView(pbs.forms.GetActionMixin,views.OneToManyListView):
    title = "Edging Plan"
    pmodel = Prescription
    model = EdgingPlan
    listform_class = EdgingPlanListForm
    context_pobject_name = "prescription"
    one_to_many_field_name = "prescription"
    urlpattern = "prescription/<int:ppk>/edgingplan/"
    urlname = "prescription_edgingplan_list"
    template_name_suffix = "_list"
    default_order = ("location","fuel_type__name","id")

    def _get_success_url(self):
        return urls.reverse("implementation:prescription_edgingplan_list",args=(self.pobject.id,))

    @property
    def deleteconfirm_url(self):
        return urls.reverse("implementation:prescription_edgingplans_delete",args=(self.pobject.id,))

    @classmethod
    def _get_extra_urlpatterns(cls):
        model_name = cls.model.__name__.lower()
        return [
            path('prescription/<int:ppk>/edgingplan/<int:pk>/deleteconfirm', cls.as_view(),{"action":"deleteconfirm"},name='prescription_edgingplan_delete_confirm'),
            path('prescription/<int:ppk>/edgingplans/delete', cls.as_view(),{"action":"deleteconfirmed"},name='prescription_edgingplans_delete'),
        ]


    """
    def post(self,*args,**kwargs):
        import ipdb;ipdb.set_trace()
        return super().post(*args,**kwargs)

    def update_context_data(self,context):
        super().update_context_data(context)
    """

pbs/implementation/views/exclusionarea.py
from django.urls import path 
from django import urls

from pbs.prescription.models import (Prescription,)
from pbs.risk.models import (Treatment,)
from pbs.implementation.models import (ExclusionArea,)
from pbs.implementation.forms import (ExclusionAreaListUpdateForm,ExclusionAreaListForm,)
from pbs.risk.forms import (TreatmentListForm,)
from dpaw_utils import views

import pbs.forms

class PrescriptionExclusionAreaListUpdateView(pbs.forms.GetActionMixin,views.OneToManyListUpdateView):
    title = "Areas to be Excluded From Ignition"
    pmodel = Prescription
    model = ExclusionArea
    listform_class = ExclusionAreaListUpdateForm
    context_pobject_name = "prescription"
    one_to_many_field_name = "prescription"
    urlpattern = "prescription/<int:ppk>/exclusionarea/"
    urlname = "prescription_exclusionarea_changelist"
    template_name_suffix = "_changelist"
    default_order = ("id",)

    def get_mediaforms(self):
        return (self.get_listform_class(),TreatmentListForm)

    def _get_success_url(self):
        return urls.reverse("implementation:prescription_exclusionarea_changelist",args=(self.pobject.id,))

    @property
    def deleteconfirm_url(self):
        return urls.reverse("implementation:prescription_exclusionareas_delete",args=(self.pobject.id,))

    @classmethod
    def _get_extra_urlpatterns(cls):
        model_name = cls.model.__name__.lower()
        return [
            path('prescription/<int:ppk>/exclusionarea/<int:pk>/deleteconfirm', cls.as_view(),{"action":"deleteconfirm"},name='prescription_exclusionarea_delete_confirm'),
            path('prescription/<int:ppk>/exclusionareas/delete', cls.as_view(),{"action":"deleteconfirmed"},name='prescription_exclusionareas_delete'),
        ]

    def get_listform_class(self):
        if self.action == 'deleteconfirm':
            return ExclusionAreaListForm
        else:
            return super().get_listform_class()

    """
    def post(self,*args,**kwargs):
        import ipdb;ipdb.set_trace()
        return super().post(*args,**kwargs)
    """

    def update_context_data(self,context):
        super().update_context_data(context)
        context["treatmentlistform"] = TreatmentListForm(instance_list=Treatment.objects.filter(register__prescription = self.pobject),request=self.request,requesturl = self.requesturl)

pbs/implementation/views/lightingsequence.py
from django.urls import path 
from django import urls

from pbs.prescription.models import (Prescription,)
from pbs.implementation.models import (LightingSequence,)
from pbs.implementation.forms import (LightingSequenceCreateForm,LightingSequenceUpdateForm,LightingSequenceListForm,)
from dpaw_utils import views

import pbs.forms

class PrescriptionLightingSequenceCreateView(pbs.forms.GetActionMixin,views.OneToManyCreateView):
    title = "Add Lighting Sequence"
    pmodel = Prescription
    model = LightingSequence
    form_class = LightingSequenceCreateForm
    context_pobject_name = "prescription"
    one_to_many_field_name = "prescription"
    urlpattern = "prescription/<int:ppk>/lightingsequence/add/"
    urlname = "prescription_lightingsequence_create"
    template_name_suffix = "_create"

    def _get_success_url(self):
        return urls.reverse("implementation:prescription_lightingsequence_list",args=(self.pobject.id,))

class PrescriptionLightingSequenceUpdateView(pbs.forms.GetActionMixin,views.OneToManyUpdateView):
    title = "Change Lighting Sequence"
    pmodel = Prescription
    model = LightingSequence
    form_class = LightingSequenceUpdateForm
    context_pobject_name = "prescription"
    one_to_many_field_name = "prescription"
    urlpattern = "prescription/<int:ppk>/lightingsequence/<int:pk>/"
    urlname = "prescription_lightingsequence_update"
    template_name_suffix = "_update"

    def _get_success_url(self):
        return urls.reverse("implementation:prescription_lightingsequence_list",args=(self.pobject.id,))


class PrescriptionLightingSequenceListView(pbs.forms.GetActionMixin,views.OneToManyListView):
    title = "Lighting Sequence"
    pmodel = Prescription
    model = LightingSequence
    listform_class = LightingSequenceListForm
    context_pobject_name = "prescription"
    one_to_many_field_name = "prescription"
    urlpattern = "prescription/<int:ppk>/lightingsequence/"
    urlname = "prescription_lightingsequence_list"
    template_name_suffix = "_list"
    default_order = ("seqno","id")

    def _get_success_url(self):
        return urls.reverse("implementation:prescription_lightingsequence_list",args=(self.pobject.id,))

    @property
    def deleteconfirm_url(self):
        return urls.reverse("implementation:prescription_lightingsequences_delete",args=(self.pobject.id,))

    @classmethod
    def _get_extra_urlpatterns(cls):
        model_name = cls.model.__name__.lower()
        return [
            path('prescription/<int:ppk>/lightingsequence/<int:pk>/deleteconfirm', cls.as_view(),{"action":"deleteconfirm"},name='prescription_lightingsequence_delete_confirm'),
            path('prescription/<int:ppk>/lightingsequences/delete', cls.as_view(),{"action":"deleteconfirmed"},name='prescription_lightingsequences_delete'),
        ]


    """
    def post(self,*args,**kwargs):
        import ipdb;ipdb.set_trace()
        return super().post(*args,**kwargs)
    """

pbs/implementation/views/operationaloverview.py
from django import urls

from pbs.prescription.models import (Prescription,)
from pbs.implementation.models import (OperationalOverview,)
from pbs.implementation.forms import (OperationalOverviewUpdateForm,)
from dpaw_utils.views import (OneToOneUpdateView,)

class PrescriptionOperationalOverviewUpdateView(OneToOneUpdateView):
    title = "Operational Overview"
    pmodel = Prescription
    model = OperationalOverview
    form_class = OperationalOverviewUpdateForm
    context_pobject_name = "prescription"
    one_to_one_field_name = "prescription"
    urlpattern = "prescription/<int:ppk>/operationaloverview/"
    urlname = "prescription_operationaloverview_update"
    template_name_suffix = "_update"

    def _get_success_url(self):
        return urls.reverse("implementation:prescription_operationaloverview_update",args=(self.pobject.id,))
    """
    def post(self,*args,**kwargs):
        import ipdb;ipdb.set_trace()
        return super().post(*args,**kwargs)
    """

templates/implementation/burningprescription_deleteconfirm.html
{% extends "../deleteconfirm.html" %}
{% load i18n %}
{% load admin_urls %}

{% block breadcrumbs %}
<ul class="breadcrumb">
  <li><a href="{% url 'prescription:prescription_list' %}">{% trans 'Regional Overview' %}</a> <span class="divider">/</span></li>
  <li><a href="{% url 'prescription:prescription_home' prescription.id %}">{{ prescription.burn_id }}</a> <span class="divider">/</span></li>
  <li><a href="{% url 'report:prescription_day_state_update' prescription.id %}">Part B</a> <span class="divider">/</span></li>
  <li><a href="{% url 'implementation:prescription_burningprescription_list' prescription.id %}">Section B5 &#x2010; Burning prescription</a> <span class="divider">/</span></li>
  {% if listform|length == 1 %}
  <li>{{listform.first.instance.fuel_type}}<span class="divider">/</span></li>
  {% endif %}
  <li>{% trans 'Delete' %}</li>
</ul>
{% endblock %}

templates/implementation/burningprescription_list.html
{% extends "../list.html" %}
{% load i18n %}

{% block breadcrumbs %}
<ul class="breadcrumb">
  <li><a href="{% url 'prescription:prescription_list' %}">{% trans 'Regional Overview' %}</a> <span class="divider">/</span></li>
  <li><a href="{% url 'prescription:prescription_home' prescription.id %}">{{prescription.burn_id}}</a> <span class="divider">/</span></li>
  <li><a href="% url 'report:prescription_day_state_update' prescription.id %}">Part B</a> <span class="divider">/</span></li>
  <li>Section B5 &#x2010;  Burning prescription</li>
</ul>
{% endblock %}

{% block content_title %}
<div class="row">
    <div class="span12" >
        <h1>Treatments</h1>
        <div class="alert alert-info">
            <strong>Note:</strong> Treatments for this section have been identified in the risk register.
        </div>

        {% include "includes/objectlist.html" with includedlistform=treatmentlistform %}
    </div>
</div>

<h1>{{title}}
    <div class="pull-right">
        <a class="btn btn-small btn-info" href="{% url 'implementation:prescription_burningprescription_create' prescription.id %}">
          <i class="icon-plus icon-white"></i>
          Create Burning Prescription
        </a>
    </div>
</h1>
{% endblock %}


{% block post_content %}
<h1>Fuel Assessment Summary
   <div class="pull-right">
   <a href="{% url 'document:prescription_taggeddocument_add' prescription.id 165 %}?nexturl={% url 'implementation:prescription_burningprescription_list' prescription.id %}" class="btn btn-info btn-small"><b><i class="icon-plus"></i> Upload Fuel Assessment Summary</b></a>
   <a class="btn btn-small btn-info" href="https://fmsb.dpaw.wa.gov.au/images/documents/fire_doctrine/forms/FIRE_872_Fuel_Assessment_Summary_Final_20130902.docx" target="_blank" ><i class="icon-download-alt"></i> Download the FIRE 872 template</a>
   </div>
</h1>
{% include "document/includes/document_list.html" with document_type="Fuel Assessment Summary"  documents=documents_165%}

<h1>Fire Behaviour Calculations
   <div class="pull-right">
   <a href="{% url 'document:prescription_taggeddocument_add' prescription.id 167 %}?nexturl={% url 'implementation:prescription_burningprescription_list' prescription.id %}" class="btn btn-info btn-small"><b><i class="icon-plus"></i> Upload Fire Behaviour Calculations</b></a>
   <a class="btn btn-small btn-info" href="https://fmsb.dpaw.wa.gov.au/images/documents/fire_doctrine/forms/FIRE_873_Forest_Fuels_Calculation_Sheet_Final_20130715.docx" target="_blank"><i class="icon-download-alt"></i> Download the FIRE 873 template</a>
   </div>
</h1>
{% include "document/includes/document_list.html" with document_type="Fuel Assessment Summary"  documents=documents_167%}

{% endblock %}

templates/implementation/burningprescription_update.html
{% extends "../change_form.html" %}
{% load i18n %}
{% load admin_urls %}

{% block breadcrumbs %}
<ul class="breadcrumb">
  <li><a href="{% url 'prescription:prescription_list' %}">{% trans 'Regional Overview' %}</a> <span class="divider">/</span></li>
  <li><a href="{% url 'prescription:prescription_home' prescription.id %}">{{ prescription.burn_id }}</a> <span class="divider">/</span></li>
  <li><a href="{% url 'report:prescription_day_state_update' prescription.id %}">Part B</a> <span class="divider">/</span></li>
  <li><a href="{% url 'implementation:prescription_burningprescription_list' prescription.id %}">Section B5 &#x2010; Burning prescription</a> <span class="divider">/</span></li>
  <li>{{form.instance.fuel_type}}</li>
</ul>
{% endblock %}

templates/implementation/edgingplan_create.html
{% extends "../change_form.html" %}
{% load i18n %}
{% load admin_urls %}

{% block breadcrumbs %}
<ul class="breadcrumb">
  <li><a href="{% url 'prescription:prescription_list' %}">{% trans 'Regional Overview' %}</a> <span class="divider">/</span></li>
  <li><a href="{% url 'prescription:prescription_home' prescription.id %}">{{ prescription.burn_id }}</a> <span class="divider">/</span></li>
  <li><a href="{% url 'report:prescription_day_state_update' prescription.id %}">Part B</a> <span class="divider">/</span></li>
  <li><a href="{% url 'implementation:prescription_edgingplan_list' prescription.id %}">Section B5 &#x2010; Edging Plan</a> <span class="divider">/</span></li>
  <li>Add</li>
</ul>
{% endblock %}

templates/implementation/edgingplan_deleteconfirm.html
{% extends "../deleteconfirm.html" %}
{% load i18n %}
{% load admin_urls %}

{% block breadcrumbs %}
<ul class="breadcrumb">
  <li><a href="{% url 'prescription:prescription_list' %}">{% trans 'Regional Overview' %}</a> <span class="divider">/</span></li>
  <li><a href="{% url 'prescription:prescription_home' prescription.id %}">{{ prescription.burn_id }}</a> <span class="divider">/</span></li>
  <li><a href="{% url 'report:prescription_day_state_update' prescription.id %}">Part B</a> <span class="divider">/</span></li>
  <li><a href="{% url 'implementation:prescription_edgingplan_list' prescription.id %}">Section B5 &#x2010; Edging Plan</a> <span class="divider">/</span></li>
  {% if listform|length == 1 %}
  <li>{{listform.first.instance.id}}<span class="divider">/</span></li>
  {% endif %}
  <li>{% trans 'Delete' %}</li>
</ul>
{% endblock %}

templates/implementation/edgingplan_list.html
{% extends "../list.html" %}
{% load i18n %}

{% block breadcrumbs %}
<ul class="breadcrumb">
  <li><a href="{% url 'prescription:prescription_list' %}">{% trans 'Regional Overview' %}</a> <span class="divider">/</span></li>
  <li><a href="{% url 'prescription:prescription_home' prescription.id %}">{{prescription.burn_id}}</a> <span class="divider">/</span></li>
  <li><a href="% url 'report:prescription_day_state_update' prescription.id %}">Part B</a> <span class="divider">/</span></li>
  <li>Section B5 &#x2010;  Edging Plan</li>
</ul>
{% endblock %}

{% block content_title %}
<h1>{{title}}
    <div class="pull-right">
        <a class="btn btn-small btn-info" href="{% url 'implementation:prescription_edgingplan_create' prescription.id %}">
          <i class="icon-plus icon-white"></i>
          Create Edging Plan
        </a>
    </div>
</h1>
{% endblock %}

templates/implementation/exclusionarea_deleteconfirm.html
{% extends "../deleteconfirm.html" %}
{% load i18n %}
{% load admin_urls %}

{% block breadcrumbs %}
<ul class="breadcrumb">
  <li><a href="{% url 'prescription:prescription_list' %}">{% trans 'Regional Overview' %}</a> <span class="divider">/</span></li>
  <li><a href="{% url 'prescription:prescription_home' prescription.id %}">{{ prescription.burn_id }}</a> <span class="divider">/</span></li>
  <li><a href="{% url 'report:prescription_day_state_update' prescription.id %}">Part B</a> <span class="divider">/</span></li>
  <li><a href="{% url 'implementation:prescription_exclusionarea_changelist' prescription.id %}">Section B5 &#x2010; Areas to be excluded from ignition</a> <span class="divider">/</span></li>
  {% if listform|length == 1 %}
  <li>{{listform.first.instance.location}}<span class="divider">/</span></li>
  {% endif %}
  <li>{% trans 'Delete' %}</li>
</ul>
{% endblock %}

templates/implementation/lightingsequence_list.html
{% extends "../list.html" %}
{% load i18n %}

{% block breadcrumbs %}
<ul class="breadcrumb">
  <li><a href="{% url 'prescription:prescription_list' %}">{% trans 'Regional Overview' %}</a> <span class="divider">/</span></li>
  <li><a href="{% url 'prescription:prescription_home' prescription.id %}">{{prescription.burn_id}}</a> <span class="divider">/</span></li>
  <li><a href="% url 'report:prescription_day_state_update' prescription.id %}">Part B</a> <span class="divider">/</span></li>
  <li>Section B5 &#x2010;  Lighting sequence</li>
</ul>
{% endblock %}

{% block content_title %}
<h1>{{title}}
    <div class="pull-right">
        <a class="btn btn-small btn-info" href="{% url 'implementation:prescription_lightingsequence_create' prescription.id %}">
          <i class="icon-plus icon-white"></i>
          Create Lighting Sequence
        </a>
    </div>
</h1>
{% endblock %}