pbs/prescription/urls.py
from .views import (PrescriptionCreateView,PrescriptionListView,PrescriptionHomeView,PrescriptionUpdateView,
        PrescriptionRegionalObjectivesUpdateView,PrescriptionObjectivesUpdateView,PrescriptionSuccessCriteriasUpdateView,
        PrescriptionPriorityJustificationsUpdateView,
        PrescriptionBriefingChecklistUpdateView,PrescriptionBriefingChecklistListView,
        )

app_name = "prescription"
urlpatterns = []

urlpatterns.extend(PrescriptionCreateView.urlpatterns())
urlpatterns.extend(PrescriptionListView.urlpatterns())
urlpatterns.extend(PrescriptionHomeView.urlpatterns())
urlpatterns.extend(PrescriptionUpdateView.urlpatterns())
urlpatterns.extend(PrescriptionRegionalObjectivesUpdateView.urlpatterns())
urlpatterns.extend(PrescriptionObjectivesUpdateView.urlpatterns())
urlpatterns.extend(PrescriptionSuccessCriteriasUpdateView.urlpatterns())
urlpatterns.extend(PrescriptionPriorityJustificationsUpdateView.urlpatterns())


urlpatterns.extend(PrescriptionBriefingChecklistListView.urlpatterns())

pbs_project/urls.py
from django.urls import include, path
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('docs/', include('django.contrib.admindocs.urls')),
    path('', include('django.contrib.auth.urls'))
]
import pbs.views
import pbs.prescription.urls
import pbs.report.urls
import pbs.risk.urls
import pbs.document.urls
import pbs.stakeholder.urls
import pbs.implementation.urls

from tastypie.api import Api

handler500 = pbs.views.handler500
handler404 = pbs.views.handler404

urlpatterns = urlpatterns + [
    path("admin/",admin.site.urls),
    path("chaining/",include('smart_selects.urls')),
    path("prescription/",include(pbs.prescription.urls,namespace="prescription")),
    path("prescription/",include(pbs.report.urls,namespace="report")),
    path("risk/",include(pbs.risk.urls,namespace="risk")),
    path("document/",include(pbs.document.urls,namespace="document")),
    path("stakeholder/",include(pbs.stakeholder.urls,namespace="stakeholder")),
    path("implementation/",include(pbs.implementation.urls,namespace="implementation"))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
for p in urlpatterns:
    print(p)

swingers/conf/project_template/project_name/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'dec_template.views.home', name='home'),
    # url(r'^dec_template/', include('dec_template.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
)

pbs/prescription/models.py
import logging
import os
from datetime import timedelta,datetime
from dateutil import tz
from decimal import Decimal

from django.contrib.gis.db import models
from django.dispatch import receiver
from django.db.models.signals import post_save,m2m_changed
from django.contrib.auth.models import User, Group
from django.urls import reverse
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db.models import Q, Max, Sum
from django.forms import ValidationError
from django.template.defaultfilters import truncatewords
from django.utils.safestring import mark_safe
from django.utils import timezone

from dpaw_utils.models import AuditMixin,ModelDictMixin,SelectOptionMixin

from pbs.risk.models import (Register, Risk, Action, Complexity, Context, Treatment)

logger = logging.getLogger("log." + __name__)

# Create your models here.
class Season(AuditMixin):
    #SEASON_SPRING = 1
    #SEASON_SUMMER = 2
    #SEASON_AUTUMN = 3
    #SEASON_WINTER = 4
    #SEASON_EARLY_DRY = 5
    #SEASON_LATE_DRY = 6
    #SEASON_WET = 7
    SEASON_ANNUAL = 8
    SEASON_CHOICES = (
        #(SEASON_SUMMER, "Summer"),
        #(SEASON_AUTUMN, "Autumn"),
        #(SEASON_WINTER, "Winter"),
        #(SEASON_SPRING, "Spring"),
        #(SEASON_EARLY_DRY, "Early Dry"),
        #(SEASON_LATE_DRY, "Late Dry"),
        #(SEASON_WET, "Wet"),
        (SEASON_ANNUAL, "Annual"),
    )

    name = models.PositiveSmallIntegerField(
        choices=SEASON_CHOICES, default=SEASON_ANNUAL)
    start = models.DateField(help_text="Start date of season")
    end = models.DateField(help_text="End date of season")

    def __str__(self):
        if self.start.year == self.end.year:
            year = self.start.year
        else:
            year = "%s/%s" % (self.start.year, self.end.year)
        return "%s %s" % (self.get_name_display(), year)

    class Meta:
        ordering = ["-start"]


class RegionManager(models.Manager):
    def get_by_natural_key(self, name):
        return self.get(name=name)

class Region(SelectOptionMixin,models.Model):
    """
    """
    name = models.CharField(max_length=64, unique=True)
    objects = RegionManager()

    def natural_key(self):
        return (self.name,)

    def __str__(self):
        return self.name


class DistrictManager(models.Manager):
    def current(self):
        # Filter queryset to return non-archived objects.
        return self.filter(archive_date__isnull=True)

    def archived(self):
        # Filter queryset to return archived objects only.
        return self.filter(archive_date__isnull=False)

    def get_by_natural_key(self, region, name):
        region = Region.objects.get_by_natural_key(region)
        return self.get(name=name, region=region)

class District(SelectOptionMixin,models.Model):
    region = models.ForeignKey(Region, on_delete=models.PROTECT)
    name = models.CharField(max_length=200, unique=True)
    code = models.CharField(max_length=3)
    archive_date = models.DateField(
        null=True, blank=True, help_text="Archive this District (prevent from creating new ePFPs)")
    objects = DistrictManager()

    def natural_key(self):
        return self.region.natural_key() + (self.name,)
    natural_key.dependencies = ['prescription.region']

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']


class ShireManager(models.Manager):
    def get_by_natural_key(self, region, district, name):
        district = District.objects.get_by_natural_key(region, district)
        return self.get(name=name, district=district)

class Shire(models.Model):
    district = models.ForeignKey(District, on_delete=models.PROTECT)
    name = models.CharField(max_length=200)
    objects = ShireManager()

    def natural_key(self):
        return self.district.natural_key() + (self.name,)
    natural_key.dependencies = ['prescription.district']

    def __str__(self):
        return "{0} ({1})".format(self.name, self.district)

    @property
    def shire_name(self):
        return str("{0} ({1})".format(str(self.name).split(',')[0], self.district))

    class Meta:
        ordering = ['name']
        unique_together = ('name', 'district')

class FuelType(models.Model):
    """
    Note that this model type is now referred to as "fuel type" in
    forms and views.
    TODO: rename the model.
    """
    name = models.CharField(max_length=200)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name


class Tenure(models.Model):
    name = models.CharField(max_length=200)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name

class Purpose(models.Model):
    name = models.CharField(max_length=200)
    display_order = models.PositiveIntegerField(default=1)

    class Meta:
        ordering = ['display_order', 'name']

    def __str__(self):
        return self.name

class ForecastArea(models.Model):
    districts = models.ManyToManyField(District)
    name = models.CharField(max_length=200)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name


class EndorsingRoleManager(models.Manager):
    def get_by_natural_key(self, name):
        return self.get(name=name)

class EndorsingRole(models.Model):
    name = models.CharField(max_length=320)
    index = models.PositiveSmallIntegerField()
    disclaimer = models.TextField()
    archived = models.BooleanField(default=False, verbose_name="Role archived?")

    objects = EndorsingRoleManager()

    def natural_key(self):
        return (self.name,)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['index']

class RegionalObjective(ModelDictMixin,AuditMixin):
    """
    """
    IMPACT_REGION = 1
    IMPACT_FMA = 2
    IMPACT_CHOICES = (
        (IMPACT_REGION, 'Region'),
        (IMPACT_FMA, 'Fire Management Area')
    )
    region = models.ForeignKey(Region, on_delete=models.PROTECT)
    impact = models.PositiveSmallIntegerField(
        choices=IMPACT_CHOICES, default=IMPACT_REGION,
        help_text="Area of application for objective",
        verbose_name="Scale of Application")
    fma_names = models.TextField(
        help_text="If the impact of this objective is Fire Management Area, "
                  "enter the names of the areas of application here",
        verbose_name="Fire Management Areas", blank=True)
    objectives = models.TextField(verbose_name="Burn objectives")

    def __str__(self):
        return self.objectives[:64]

    class Meta:
        verbose_name = 'Regional Fire Management Plan Objective'
        verbose_name_plural = 'Regional Fire Management Plan Objectives'

class SMEAC(models.Model):
    category = models.CharField(max_length=200)

    def __str__(self):
        return self.category

class DefaultBriefingChecklist(models.Model):
    smeac = models.ForeignKey(SMEAC, verbose_name="SMEACS", on_delete=models.PROTECT)
    title = models.CharField(max_length=200)

class Prescription(ModelDictMixin,AuditMixin):
    """
    A Prescription is the core object in the system. It should contain all the
    top level attributes imported from Prescription Program Planning except
    Purposes and Objectives.
    """
    PRIORITY_UNSET = 0
    PRIORITY_LOW = 1
    PRIORITY_MEDIUM = 2
    PRIORITY_HIGH = 3
    PRIORITY_NOT_APPLICABLE = 4

    PRIORITY_CHOICES = (
        (PRIORITY_UNSET, 'Unset'),
        (PRIORITY_LOW, '1'),
        (PRIORITY_MEDIUM, '2'),
        (PRIORITY_HIGH, '3')
    )

    SENSING_PRIORITY_CHOICES = (
        (PRIORITY_HIGH, 'High'),
        (PRIORITY_MEDIUM, 'Medium'),
        (PRIORITY_LOW, 'Low'),
        (PRIORITY_NOT_APPLICABLE, 'Not Applicable'),
    )

    # # TODO: Remove when PBS-1551 is closed
    # ALLOCATION_CHOICES = (
    #       (42, '42 - Native forest'),
    #       (43, '43 - Plantations'),
    #       (72, '72 - Prescribed fire'),
    #       (7204, '72-04 - Recoupable projects'),
    # )

    PLANNING_DRAFT = 1
    PLANNING_SUBMITTED = 2
    PLANNING_APPROVED = 3
    PLANNING_CHOICES = (
        (PLANNING_DRAFT, 'Draft'),
        (PLANNING_SUBMITTED, 'Seeking Corporate Approval'),
        (PLANNING_APPROVED, 'Corporate Approved'),
    )

    ENDORSEMENT_DRAFT = 1
    ENDORSEMENT_SUBMITTED = 2
    ENDORSEMENT_APPROVED = 3
    ENDORSEMENT_CHOICES = (
        (ENDORSEMENT_DRAFT, 'Not Endorsed'),
        (ENDORSEMENT_SUBMITTED, 'Seeking Endorsement'),
        (ENDORSEMENT_APPROVED, 'Endorsed'),
    )

    APPROVAL_DRAFT = 1
    APPROVAL_SUBMITTED = 2
    APPROVAL_APPROVED = 3
    APPROVAL_CHOICES = (
        (APPROVAL_DRAFT, 'Not Approved'),
        (APPROVAL_SUBMITTED, 'Seeking Approval'),
        (APPROVAL_APPROVED, 'Approved'),
    )

    IGNITION_NOT_STARTED = 1
    IGNITION_COMMENCED = 2
    IGNITION_COMPLETE = 3
    IGNITION_STATUS_CHOICES = (
        (IGNITION_NOT_STARTED, 'No Ignitions'),
        (IGNITION_COMMENCED, 'Ignition Commenced'),
        (IGNITION_COMPLETE, 'Ignition Completed'),
    )

    STATUS_OPEN = 1
    STATUS_CLOSED = 2
    STATUS_CHOICES = (
        (STATUS_OPEN, 'Burn Open'),
        (STATUS_CLOSED, 'Burn Closed'),
    )

    YES_NO_NULL_CHOICES = (
        (None, '-----'),
        (False, 'No'),
        (True, 'Yes'),
    )

    INT_CHOICES = [(i, i) for i in range(1, 100)]

    today = timezone.now().date()
    fin_year =  today.year if today.month <= 6 else today.year + 1
    yr1 = str(fin_year - 1) + '/' + str(fin_year)
    yr2 = str(fin_year)     + '/' + str(fin_year + 1)
    yr3 = str(fin_year + 1) + '/' + str(fin_year + 2)
    yr4 = str(fin_year + 2) + '/' + str(fin_year + 3)
    FNCL_YEAR_CHOICES = [
        [yr1, yr1],
        [yr2, yr2],
        [yr3, yr3],
        [yr4, yr4],
    ]

    prev_yr1 = str(fin_year - 2) + '/' + str(fin_year - 1)
    prev_yr2 = str(fin_year - 3) + '/' + str(fin_year - 2)
    prev_yr3 = str(fin_year - 4) + '/' + str(fin_year - 3)
    prev_yr4 = str(fin_year - 5) + '/' + str(fin_year - 4)

pbs/prescription/views.py
# Create your views here.

pbs/prescription/views/briefingchecklist.py
from django.urls import path 
from django import urls

from pbs.prescription.models import (Prescription,BriefingChecklist,)
from pbs.prescription.forms import (BriefingChecklistUpdateForm,BriefingChecklistListForm,)
from dpaw_utils import views

import pbs.forms

class PrescriptionBriefingChecklistUpdateView(pbs.forms.GetActionMixin,views.OneToManyUpdateView):
    title = "Change Breifing Checklist"
    pmodel = Prescription
    model = BriefingChecklist
    form_class = BriefingChecklistUpdateForm
    context_pobject_name = "prescription"
    one_to_many_field_name = "prescription"
    urlpattern = "prescription/<int:ppk>/briefingchecklist/<int:pk>/"
    urlname = "prescription_briefingchecklist_update"
    template_name_suffix = "_update"

    def _get_success_url(self):
        return urls.reverse("implementation:prescription_briefingchecklist_list",args=(self.pobject.id,))


class PrescriptionBriefingChecklistListView(pbs.forms.GetActionMixin,views.OneToManyListView):
    title = "Briefing Checklist"
    pmodel = Prescription
    model = BriefingChecklist
    listform_class = BriefingChecklistListForm
    context_pobject_name = "prescription"
    one_to_many_field_name = "prescription"
    urlpattern = "prescription/<int:ppk>/briefingchecklist/"
    urlname = "prescription_briefingchecklist_list"
    template_name_suffix = "_list"
    default_order = ("smeac","id")

    def _get_success_url(self):
        return urls.reverse("prescription:prescription_briefingchecklist_list",args=(self.pobject.id,))

    @property
    def deleteconfirm_url(self):
        return urls.reverse("prescription:prescription_briefingchecklists_delete",args=(self.pobject.id,))

    @classmethod
    def _get_extra_urlpatterns(cls):
        model_name = cls.model.__name__.lower()
        return [
            path('prescription/<int:ppk>/briefingchecklist/<int:pk>/deleteconfirm', cls.as_view(),{"action":"deleteconfirm"},name='prescription_briefingchecklist_delete_confirm'),
            path('prescription/<int:ppk>/briefingchecklists/delete', cls.as_view(),{"action":"deleteconfirmed"},name='prescription_briefingchecklists_delete'),
        ]


    """
    def post(self,*args,**kwargs):
        import ipdb;ipdb.set_trace()
        return super().post(*args,**kwargs)
    """
    def update_context_data(self,context):
        super().update_context_data(context)
        context["documents"] = self.pobject.document_set.filter(tag__id=182)

pbs/prescription/views/regionalobjective.py
from django.urls import path 
from django import urls

from pbs.prescription.models import (Prescription,RegionalObjective)
from pbs.prescription.forms import (RegionalObjectiveListForm,)
from dpaw_utils import views
import pbs.forms

class PrescriptionRegionalObjectivesUpdateView(pbs.forms.GetActionMixin,views.ManyToManyListView):
    title = "Select Regional Fire Management Plan Objectives"
    pmodel = Prescription
    model = RegionalObjective
    listform_class = RegionalObjectiveListForm
    context_pobject_name = "prescription"
    many_to_many_field_name = "regional_objectives"
    related_field_name = "prescription"
    urlpattern = "/prescription/<int:ppk>/add/regionalobjectives/"
    urlname = "prescription_regionalobjectives_update"
    template_name_suffix = "_list"

    @property
    def deleteconfirm_url(self):
        return urls.reverse("prescription:prescription_regionalobjectives_delete",args=(self.pobject.id,))

    @classmethod
    def _get_extra_urlpatterns(cls):
        model_name = cls.model.__name__.lower()
        return [
            path('prescription/<int:ppk>/regionalobjective/<int:pk>/deleteconfirm', cls.as_view(),{"action":"deleteconfirm"},name='prescription_regionalobjective_delete_confirm'),
            path('prescription/<int:ppk>/regionalobjectives/delete', cls.as_view(),{"action":"deleteconfirmed"},name='prescription_regionalobjectives_delete'),
        ]

    def _get_success_url(self):
        return urls.reverse("risk:context_update",args=(self.pobject.id,))

    def update_context_data(self,context):
        super().update_context_data(context)
        qs = self.model.objects.filter(region=self.pobject.region.id).exclude(prescription=self.pobject)
        context["unselectedlistform"] = self.get_listform_class()(instance_list=qs,request=self.request,requesturl = self.requesturl)
        context["object_list_length"] = len(qs) + len(self.object_list)

templates/prescription/briefingchecklist_deleteconfirm.html
{% extends "../deleteconfirm.html" %}
{% load i18n %}
{% load admin_urls %}

{% block breadcrumbs %}
<ul class="breadcrumb">
  <li><a href="{% url 'prescription:prescription_list' %}">{% trans 'Regional Overview' %}</a> <span class="divider">/</span></li>
  <li><a href="{% url 'prescription:prescription_home' prescription.id %}">{{ prescription.burn_id }}</a> <span class="divider">/</span></li>
  <li><a href="{% url 'report:prescription_day_state_update' prescription.id %}">Part B</a> <span class="divider">/</span></li>
  <li><a href="{% url 'prescription:prescription_briefingchecklist_list' prescription.id %}">Briefing Checklist</a> <span class="divider">/</span></li>
  {% if listform|length == 1 %}
  <li>{{listform.first.instance.title}}<span class="divider">/</span></li>
  {% endif %}
  <li>{% trans 'Delete' %}</li>
</ul>
{% endblock %}

templates/prescription/briefingchecklist_list.html
{% extends "../list.html" %}
{% load i18n %}
{% load pbs_utils %}

{% block content_title %}
<div class="row">
    <div class="span12" >
	<h1>Checklist Report
            <span class="pull-right">
	    <a class="btn btn-small btn-info" href=""><i class="icon-download-alt"></i> Download the Briefing Checklist template</a>
           <a href="{% url 'document:prescription_taggeddocument_add' prescription.id 182 %}?nexturl={% url 'prescription:prescription_briefingchecklist_list' prescription.id %}" class="btn btn-info btn-small"><b><i class="icon-plus"></i> Upload Briefing Checklist</b></a>
            </span>
        </h1>
        {% include "document/includes/document_list.html" with document_type="Briefing Checklist" %}
    </div>
</div>
{{block.super}}
{% endblock %}


{% block breadcrumbs %}

<ul class="breadcrumb">
  <li><a href="{% url 'prescription:prescription_list' %}">{% trans 'Regional Overview' %}</a> <span class="divider">/</span></li>
  <li><a href="{% url 'prescription:prescription_home' prescription.id %}">{{ prescription.burn_id }}</a> <span class="divider">/</span></li>
  <li><a href="% url 'report:prescription_day_state_update' prescription.id %}">Part B</a> <span class="divider">/</span></li>
  <li>Section B8 &#x2010; Briefing Checklist</li>
</ul>

{% endblock %}



{% block list_content %}
    <table id="{{listform.model_name_lower}}_result_list" class="table table-striped table-condensed table-hober table-fixed-header">
        <thead>
            <tr>
                {% for field in listform.boundfields %}
                {% if field.name != 'smeac' %}
                {% call_method field "html_header" "<th{attrs}><div class=\"text\"> {label}</div></th>"%}
                {% endif %}
                {% endfor %}
            </tr>
        </thead>
        <tbody>
            {% for form in listform %}
            {% if smeac != form.smeac.value %}
            <tr>
                <th colspan="{{listform.boundfieldlength}}">{{form.smeac}}</th>
            </tr>
            {% setvar form.smeac.value as smeac %}
            {% endif %}
            <tr> 
                {% for field in form.boundfields %}
                    {% if field.name == 'title' %}
                    {% call_method field "html" "<td{attrs} style='padding-left:30px'>{widget}</td>"%}
                    {% elif field.name != 'smeac' %}
                    {% call_method field "html" "<td{attrs}>{widget}</td>"%}
                    {% endif %}
                {% endfor %}
            </tr>
            {% endfor %}

        </tbody>
    </table>

{% endblock %}

templates/prescription/objective_changelist.html
{% extends "../changelist.html" %}
{% load i18n %}

{% block breadcrumbs %}
<ul class="breadcrumb">
  <li><a href="{% url 'prescription:prescription_list' %}">{% trans 'Regional Overview' %}</a> <span class="divider">/</span></li>
  <li><a href="{% url 'prescription:prescription_home' prescription.id %}">{{ prescription.burn_id }}</a> <span class="divider">/</span></li>
  <li><a href="{% url 'report:prescription_pre_state_update' prescription.id %}">Part A</a> <span class="divider">/</span></li>
  <li>Section A3 &#x2010; Burn Objectives</li>
</ul>


<h1>Regional Fire Management Plan Objectives</h1>
<table class="table table-striped table-condensed">
  <thead>
    <tr>
      <th scope="col">Region</th>
      <th scope="col">Scale of Application</th>
      <th scope="col">Fire Management Areas</th>
      <th scope="col" colspan=2>Objectives</th>
    </tr>
  </thead>
  <tbody>
    {% for objective in prescription.regional_objectives.all %}
    <tr>
      <td>{{ objective.region }}</td>
      <td>{{ objective.get_impact_display }}</td>
      <td>{% if objective.fma_names %}{{ objective.fma_names }}{% else %}None{% endif %}</td>
      <td>{{ objective.objectives }}</td>
      <td>
        {% if 'prescription.delete_regionalobjective' in request.user.get_all_permissions %}
        <a href="{% url 'prescription:prescription_regionalobjective_delete_confirm' prescription.id objective.id %}" class="btn btn-mini alert-error" title="Delete regional objective"><i class="icon-trash"></i></a>
        {% endif %}
      </td>
    </tr>
    {% empty %}
    <tr>
      <td colspan="4">There are no Regional Fire Management Plan objectives.</td>
    </tr>
    {% endfor %}
  </tbody>
</table>

{% endblock %}

templates/prescription/objective_deleteconfirm.html
{% extends "../deleteconfirm.html" %}
{% load i18n %}
{% load admin_urls %}

{% block breadcrumbs %}
<ul class="breadcrumb">
  <li><a href="{% url 'prescription:prescription_list' %}">{% trans 'Regional Overview' %}</a> <span class="divider">/</span></li>
  <li><a href="{% url 'prescription:prescription_home' prescription.id %}">{{ prescription.burn_id }}</a> <span class="divider">/</span></li>
  <li><a href="{% url 'prescription:prescription_objective_changelist' prescription.id %}">Burn Objectives</a> <span class="divider">/</span></li>
  {% if listform|length == 1 %}
  <li>{{listform.first.id.value}}<span class="divider">/</span></li>
  {% endif %}
  <li>{% trans 'Delete' %}</li>
</ul>
{% endblock %}

templates/prescription/prescription_list.html
{% extends "../list.html" %}
{% load i18n %}

templates/prescription/regionalobjective_deleteconfirm.html
{% extends "../deleteconfirm.html" %}
{% load i18n %}
{% load admin_urls %}

{% block breadcrumbs %}
<ul class="breadcrumb">
  <li><a href="{% url 'prescription:prescription_list' %}">{% trans 'Regional Overview' %}</a> <span class="divider">/</span></li>
  <li><a href="{% url 'prescription:prescription_home' prescription.id %}">{{ prescription.burn_id }}</a> <span class="divider">/</span></li>
  <li><a href="{% url 'report:prescription_pre_state_update' prescription.id %}">Part A</a> <span class="divider">/</span></li>
  <li><a href="{% url 'prescription:prescription_regionalobjectives_update' prescription.id %}">Regional Objectives</a> <span class="divider">/</span></li>
  <li>{% trans 'Delete regional objective' %}</li>
</ul>
{% endblock %}

templates/prescription/successcriteria_changelist.html
{% extends "../changelist.html" %}
{% load i18n %}

{% block breadcrumbs %}
<ul class="breadcrumb">
  <li><a href="{% url 'prescription:prescription_list' %}">{% trans 'Regional Overview' %}</a> <span class="divider">/</span></li>
  <li><a href="{% url 'prescription:prescription_home' prescription.id %}">{{ prescription.burn_id }}</a> <span class="divider">/</span></li>
  <li><a href="% url 'report:prescription_pre_state_update' object.id %}">Part A</a> <span class="divider">/</span></li>
  <li>Section A3 &#x2010; Success Criteria</li>
</ul>


<h1>Regional Fire Management Plan Objectives</h1>
<table class="table table-striped table-condensed">
  <thead>
    <tr>
      <th scope="col">Region</th>
      <th scope="col">Scale of Application</th>
      <th scope="col">Fire Management Areas</th>
      <th scope="col">Objectives</th>
    </tr>
  </thead>
  <tbody>
    {% for objective in prescription.regional_objectives.all %}
    <tr>
      <td>{{ objective.region }}</td>
      <td>{{ objective.get_impact_display }}</td>
      <td>{% if objective.fma_names %}{{ objective.fma_names }}{% else %}None{% endif %}</td>
      <td>{{ objective.objectives }}</td>
    </tr>
    {% empty %}
    <tr>
      <td colspan="4">There are no Regional Fire Management Plan objectives.</td>
    </tr>
    {% endfor %}
  </tbody>
</table>

<div class="row">
<div class="span5">
<h1>Burn Objectives</h1>
<ul>
    {% for objective in prescription.objective_set.all %}
    <li>{{objective.objectives}}</li>
    {% endfor %}
</ul>
</div>
<div class="span5 offset1">
<h1>Burn Purposes</h1>
<ul>
    {% for purpose in prescription.purposes.all %}
    <li>{{purpose.name}}</li>
    {% endfor %}
</ul>
</div>
</div>
{% endblock %}

templates/prescription/successcriteria_deleteconfirm.html
{% extends "../deleteconfirm.html" %}
{% load i18n %}
{% load admin_urls %}

{% block breadcrumbs %}
<ul class="breadcrumb">
  <li><a href="{% url 'prescription:prescription_list' %}">{% trans 'Regional Overview' %}</a> <span class="divider">/</span></li>
  <li><a href="{% url 'prescription:prescription_home' prescription.id %}">{{ prescription.burn_id }}</a> <span class="divider">/</span></li>
  <li><a href="{% url 'prescription:prescription_successcriteria_changelist' prescription.id %}">Success Criterias</a> <span class="divider">/</span></li>
  {% if listform|length == 1 %}
  <li>{{listform.first.id.value}}<span class="divider">/</span></li>
  {% endif %}
  <li>{% trans 'Delete' %}</li>
</ul>
{% endblock %}