pbs/document/urls.py
from .views import (PrescriptionDocumentCreateView,PrescriptionDocumentsView)


app_name = "document"
urlpatterns = []

urlpatterns.extend(PrescriptionDocumentCreateView.urlpatterns())
urlpatterns.extend(PrescriptionDocumentsView.urlpatterns())

pbs_project/urls.py
from django.urls import include, path
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('docs/', include('django.contrib.admindocs.urls')),
    path('', include('django.contrib.auth.urls'))
]
import pbs.views
import pbs.prescription.urls
import pbs.report.urls
import pbs.risk.urls
import pbs.document.urls
import pbs.stakeholder.urls
import pbs.implementation.urls

from tastypie.api import Api

handler500 = pbs.views.handler500
handler404 = pbs.views.handler404

urlpatterns = urlpatterns + [
    path("admin/",admin.site.urls),
    path("chaining/",include('smart_selects.urls')),
    path("prescription/",include(pbs.prescription.urls,namespace="prescription")),
    path("prescription/",include(pbs.report.urls,namespace="report")),
    path("risk/",include(pbs.risk.urls,namespace="risk")),
    path("document/",include(pbs.document.urls,namespace="document")),
    path("stakeholder/",include(pbs.stakeholder.urls,namespace="stakeholder")),
    path("implementation/",include(pbs.implementation.urls,namespace="implementation"))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
for p in urlpatterns:
    print(p)

swingers/conf/project_template/project_name/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'dec_template.views.home', name='home'),
    # url(r'^dec_template/', include('dec_template.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
)

pbs/document/forms.py
from django import forms
from pbs.document.models import DocumentTag, Document


class DocumentForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(DocumentForm, self).__init__(*args, **kwargs)
        if (kwargs.get('initial') is not None and
                kwargs['initial'].get('tag') is not None and
                DocumentTag.objects.filter(id=int(kwargs['initial']['tag']))):
            # hide the tag choice list if the tag is preselected
            self.fields['tag'].widget = forms.HiddenInput()

    class Meta:
        model = Document

pbs/document/forms/document.py
from pbs.forms import (BUTTON_ACTIONS,OPTION_ACTIONS)
from pbs.document.models import (Document,)

from dpaw_utils import forms

class DocumentCleanMixin(object):
    pass

class DocumentConfigMixin(object):
    class Meta:
        field_classes_config = {
            "__default__":forms.fields.CharField,
            "document_archived.filter":forms.fields.NullBooleanField,
            "categoryid":forms.fields.IntegerField,
            "modifierid":forms.fields.IntegerField,
            "q":forms.fields.CharField,
            "modifiedrange.filter":forms.fields.CharField,
            "delete":forms.fields.AliasFieldFactory(Document,"id",field_class=forms.fields.IntegerField),
            "tag.filter":forms.fields.OverrideFieldFactory(Document,"tag",field_params={"required":False})
        }
        labels = {
            "created":"Uploaded on",
            "creator":"Uploaded by",
            "document_archived":"Archived?",
            "document_created":"Document Created",
            "delete":"",
            "categoryid":"Category",
            "modifierid":"Modifier",
            "q":"Search"
        }
        widgets_config = {
            "__default__.view":forms.widgets.TextDisplay(),
            "__default__.edit":forms.widgets.TextInput(),
            "__default__.filter":forms.widgets.HiddenInput(),
            "document.edit":forms.widgets.TemplateWidgetFactory(forms.widgets.FileInput,"{{}} <span>{}</span>".format(Document._meta.get_field('document').help_text))(attrs={"style":"height:35px"}),
            "document_created.view":forms.widgets.DatetimeDisplay("%d-%m-%Y"),
            "document_created.edit":forms.widgets.DatetimeInput(),
            "modifiedrange.filter":forms.widgets.TextInput(),
            "created.view":forms.widgets.DatetimeDisplay("%d-%m-%Y %H:%M"),
            "document_archived.view":forms.widgets.ImgBooleanDisplay(),
            "modified.view":forms.widgets.DatetimeDisplay("%d-%m-%Y %H:%M"),
            "delete.view":forms.widgets.HyperlinkFactory("id","document:prescription_documents_delete_confirm",ids=[("id","pk"),("prescription","ppk")],querystring="nexturl={nexturl}",parameters=[("request_full_path","nexturl")],template='<img onclick="window.location=\'{url}\'" src="/static/img/delete.png" style="width:16px;height:16px;cursor:pointer"></img>'),
            "tag.filter":forms.widgets.HiddenInput(),
            "categoryid.filter":forms.widgets.HiddenInput(),
            "document_archived.filter":forms.widgets.HiddenInput(),
            "modifiedrange.filter":forms.widgets.HiddenInput(),
            "modifierid.filter":forms.widgets.HiddenInput(),
            "q.filter":forms.widgets.TemplateWidgetFactory(forms.widgets.TextInput,"""
                <div class="input-prepend input-append">
                    <span class="add-on"><i class="icon-search"></i></span>
                    {}
                    <button class="btn" type="submit">Search</button>
                </div>
            """)(attrs={"style":"width:160px"})
        }

class DocumentFilterForm(DocumentConfigMixin,forms.FilterForm):
    all_buttons = [
        BUTTON_ACTIONS["update_selection"],
    ]

    class Meta:
        model = Document
        purpose = ('filter',"view")
        all_fields = ("tag","categoryid","document_archived","modifiedrange","modifierid","q")

class DocumentBaseForm(DocumentCleanMixin,DocumentConfigMixin,forms.ModelForm):
    class Meta:
        pass

class DocumentCreateForm(forms.EditableFieldsMixin,DocumentBaseForm):
    all_buttons = [
        BUTTON_ACTIONS["back"],
        BUTTON_ACTIONS["upload"],
    ]
    class Meta:
        model = Document
        purpose = ('edit',"view")
        all_fields = ("category","tag","document","document_created","document_archived")
        editable_fields = ("category","tag","document","document_created","document_archived")

class TaggedDocumentCreateForm(forms.EditableFieldsMixin,DocumentBaseForm):
    all_buttons = [
        BUTTON_ACTIONS["back"],
        BUTTON_ACTIONS["upload"],
    ]
    class Meta:
        model = Document
        purpose = (('tagged','edit'),"view")
        all_fields = ("tag","document",)
        editable_fields = ("tag","document",)
        ordered_fields = ("document",)

class DocumentUpdateForm(forms.EditableFieldsMixin,DocumentBaseForm):
    all_buttons = [
        BUTTON_ACTIONS["back"],
        BUTTON_ACTIONS["upload"],
    ]
    class Meta:
        model = Document
        purpose = ('edit','view')
        all_fields = ("document",)
        editable_fields = ("document",)


class DocumentBaseListForm(DocumentConfigMixin,forms.ListForm):
    class Meta:
        purpose = (None,('list','view'))

class DocumentListForm(DocumentBaseListForm):
    all_actions = [
        OPTION_ACTIONS["delete_selected_documents"],
        OPTION_ACTIONS["archive_selected_documents"],
    ]
    def __init__(self, *args, **kwargs):
        super(DocumentListForm, self).__init__(*args, **kwargs)

    class Meta:
        model = Document
        widths = {
            "tag":"220px"
        }
        all_fields = ("tag","category","document_archived","document_created","created","creator","delete")
        
        editable_fields = []


class DocumentConfirmListForm(DocumentBaseListForm):
    all_actions = [
        OPTION_ACTIONS["delete_selected_documents"],
        OPTION_ACTIONS["archive_selected_documents"],
    ]
    def __init__(self, *args, **kwargs):
        super(DocumentConfirmListForm, self).__init__(*args, **kwargs)

    class Meta:
        model = Document
        all_fields = ("tag","category","document","document_archived","created","creator","modified","modifier")
        
        editable_fields = []

pbs/document/views/document.py
from django.urls import path 
from django import urls
from django.db import transaction
from django.http import (HttpResponseRedirect,)
from django.contrib import messages

from django_downloadview import ObjectDownloadView

from pbs.document.models import (Document,DocumentTag,documentcategory_list)
from pbs.document.filters import (DocumentFilter,)
from pbs.prescription.models import (Prescription,)
from pbs.document.forms import (TaggedDocumentCreateForm,DocumentCreateForm,DocumentListForm,DocumentConfirmListForm,DocumentFilterForm)
import pbs.forms
from dpaw_utils import views
from dpaw_utils.forms.utils import ChainDict
from dpaw_utils.forms import filters

class PrescriptionDocumentCreateView(pbs.forms.GetActionMixin,views.RequestActionMixin,views.SendDataThroughUrlMixin,views.OneToManyCreateView):
    pmodel = Prescription
    model = Document
    context_pobject_name = "prescription"
    one_to_many_field_name = "prescription"
    urlpattern = "prescription/<int:ppk>/document/add"
    urlname = "prescription_document_add"
    template_name_suffix = "_add"
    default_post_action = "upload"

    data_in_url = True

    @classmethod
    def _get_extra_urlpatterns(cls):
        return [
            path('<int:pk>/download', ObjectDownloadView.as_view(model=Document, file_field='document'),{"action":"download"},name='document_download'),
            path('prescription/<int:ppk>/document/tag/<int:tag>/add', cls.as_view(),name='prescription_taggeddocument_add'),
        ]

    @property
    def title(self):
        try:
            form = self.get_form()
            return "Add {} docment".format(form.instance.tag.name)
        except:
            return "Add document"

    def get_form_class(self):
        if "tag" in self.kwargs:
            return TaggedDocumentCreateForm
        else:
            return DocumentCreateForm

    def _get_success_url(self):
        return urls.reverse("document:prescription_document_list",args=(self.pobject.id,))

class PrescriptionDocumentsView(pbs.forms.GetActionMixin,views.OneToManyListView):
    pmodel = Prescription
    model = Document
    filter_class = DocumentFilter
    filterform_class = DocumentFilterForm
    listform_class = DocumentListForm
    context_pobject_name = "prescription"
    one_to_many_field_name = "prescription"
    urlpattern = "prescription/<int:ppk>/document/"
    urlname = "prescription_document_list"
    filtertool = False

    @classmethod
    def _get_extra_urlpatterns(cls):
        return [
            path('prescription/<int:ppk>/document/<int:pk>/deleteconfirm', cls.as_view(),{"action":"deleteconfirm"},name='prescription_documents_delete_confirm'),
            path('prescription/<int:ppk>/document/delete', cls.as_view(),{"action":"deleteconfirmed"},name='prescription_documents_delete'),
            path('prescription/<int:ppk>/document/<int:pk>/archiveconfirm', cls.as_view(),{"action":"archiveconfirm"},name='prescription_documents_archive_confirm'),
            path('prescription/<int:ppk>/document/archive', cls.as_view(),{"action":"archiveconfirmed"},name='prescription_documents_archive'),
            path('prescription/<int:ppk>/document/tag/<int:tag>/', cls.as_view(),name='prescription_taggeddocument_list'),
        ]


    @property
    def template_name_suffix(self):
        if "tag" in self.kwargs:
            return "_tagged_list"
        else:
            return "_list"

    @property
    def title(self):
        try:
            return "{} List".format(DocumentTag.objects.get(id = self.kwargs["tag"]).name)
        except:
            return "Document List"


    @property
    def deleteconfirm_url(self):
        return urls.reverse("document:prescription_documents_delete",args=(self.pobject.id,))

    @property
    def archiveconfirm_url(self):
        return urls.reverse("document:prescription_documents_archive",args=(self.pobject.id,))

    def get_filterform_data(self):
        try:
            return ChainDict([{"tag":self.kwargs["tag"]},self.request.GET,{"document_archived":False}])
        except:
            return self.request.GET

    def _get_success_url(self):
        return urls.reverse("document:prescription_document_list",args=(self.pobject.id,))

    def get_listform_class(self):
        if self.action:
            return DocumentConfirmListForm
        else:
            return DocumentListForm

    def update_context_data(self,context):
        super().update_context_data(context)
        try:
            context["tag"] = DocumentTag.objects.get(id = self.kwargs["tag"])
        except:
            context["archivestatuslist"] = ((True,"Yes"),(False,"No"))
            context["categorylist"] = documentcategory_list
            context["modifiedlist"] = filters.DateRangeFilter.choices
            userlist = set()
            for o in self.object_list:
                if o.modifier:
                    userlist.add(o.modifier)
            context["modifierlist"] = sorted(userlist,key=lambda u:u.username)

    def archiveconfirmed_post(self):
        document_list = self.get_queryset_4_selected()
        for doc in document_list:
            try:
                doc.document_archived = True
                doc.save(update_fields=["document_archived","modifier","modified"])
            except Exception as ex:
                messages.add_message(self.request,messages.ERROR,"Failed to archive document {} dut to {}".format(doc, ex))

        return HttpResponseRedirect(self.get_success_url())

templates/document/document_add.html
{% extends "../change_form.html" %}
{% load i18n %}
{% load staticfiles admin_modify %}
{% comment%}
{% load admin_urls admin_list %}

{% endcomment%}
{% block breadcrumbs %}
<ul class="breadcrumb">
  <li><a href="{% url 'prescription:prescription_list' %}">{% trans 'Regional Overview' %}</a> <span class="divider">/</span></li>
  <li><a href="{% url 'prescription:prescription_home' prescription.id %}">{{prescription.burn_id}}</a> <span class="divider">/</span></li>
  <li><a href="">Document</a> <span class="divider">/</span></li>
  <li>Add Document</li>
</ul>
{% endblock %}

templates/document/document_archiveconfirm.html
{% extends "archiveconfirm.html" %}
{% load i18n %}
{% load admin_urls %}

{% block breadcrumbs %}
<ul class="breadcrumb">
  <li><a href="{% url 'prescription:prescription_list' %}">{% trans 'Regional Overview' %}</a> <span class="divider">/</span></li>
  <li><a href="{% url 'prescription:prescription_home' prescription.id %}">{{ prescription.burn_id }}</a> <span class="divider">/</span></li>
  <li><a href="">Document</a> <span class="divider">/</span></li>
  <li>Archive</li>
</ul>
{% endblock %}

templates/document/document_create.html
{% extends "../change_form.html" %}
{% load i18n %}
{% load staticfiles admin_modify %}
{% comment%}
{% load admin_urls admin_list %}

{% endcomment%}
{% block breadcrumbs %}
<ul class="breadcrumb">
  <li><a href="{% url 'prescription:prescription_list' %}">{% trans 'Regional Overview' %}</a> <span class="divider">/</span></li>
  <li><a href="{% url 'prescription:prescription_home' prescription.id %}">{{prescription.burn_id}}</a> <span class="divider">/</span></li>
  <li><a href="">Document</a> <span class="divider">/</span></li>
  <li>Add documen</li>
</ul>
{% endblock %}

{% block form_content %}
{{form.tag}}
<table class="table table-bordered table-striped table-condensed">
    <tbody>
        <tr>
            <th class="cbas">Document *</th>
            <td class="cbas">{{form.document}}</td>
        </tr>
    </tbody>
</table>
{% endblock %}

templates/document/document_deleteconfirm.html
{% extends "deleteconfirm.html" %}
{% load i18n %}
{% load admin_urls %}

{% block breadcrumbs %}
<ul class="breadcrumb">
  <li><a href="{% url 'prescription:prescription_list' %}">{% trans 'Regional Overview' %}</a> <span class="divider">/</span></li>
  <li><a href="">Document</a> <span class="divider">/</span></li>
  <li><a href="">Documents</a> <span class="divider">/</span></li>
  <li><a href="">{{object_list.0.document.name}}</a> <span class="divider">/</span></li>
  <li>Delete</li>
</ul>
{% endblock %}

templates/document/document_list.html
{% extends "../list_2panels.html" %}
{% load i18n %}
{% load pbs_utils %}

{% block breadcrumbs %}
<ul class="breadcrumb">
  <li><a href="{% url 'prescription:prescription_list' %}">{% trans 'Regional Overview' %}</a> <span class="divider">/</span></li>
  <li><a href="{% url 'prescription:prescription_home' prescription.id %}">{{prescription.burn_id}}</a> <span class="divider">/</span></li>
  <li><a href="">Document</a> <span class="divider">/</span></li>
  {% if tag %}
  <li>{{tag.name}}</li>
  {% endif %}
</ul>
{% endblock %}

{% block content_title %}
<h1>{{ title }}
    <div class="pull-right">
        <a class="btn btn-small btn-info" href="{% url 'document:prescription_document_add' prescription.id %}?nexturl={{listform.fullpath}}">
            <i class="icon-plus icon-white"></i> Add document
        </a>
    </div>
</h1>
{% endblock %}


{% block rightpanel %}
<div class="span3">
  <h5>Filter</h5>
    <form id="changelist-search" action="" method="get">
        {% for field in filterform %}
            {% if not field.is_hidden or field.hascleanvalue %}
                {% call_method field "html"  %}
            {% endif %}
        {% endfor %}
    </form>
  {% url 'document:prescription_document_list' prescription.id as documenturl %}
  {% setvar filterform.document_archived.cleanvalue as document_archived %}
  {% call_method listform "get_querystring" "document_archived" as querystring %}
  <ul class="nav nav-list">
    <li class="nav-header">BY ARCHIVED DOCUMENT</li>
    <li {% if document_archived is None %}class="active"{% endif %}><a href="{{documenturl}}{{querystring}}">All</a></li>
    {% for option in archivestatuslist %}
    <li  {% if document_archived == option.0 %}class="active"{% endif %}><a href="{{documenturl}}{% addurlparameter querystring "document_archived" option.0|urlencode %}">{{option.1}}</a></li>
    {% endfor %}
  </ul>

  <br>
  {% setvar filterform.categoryid.cleanvalue as categoryid %}
  {% call_method listform "get_querystring" "categoryid" as querystring %}
  <ul class="nav nav-list">
    <li class="nav-header">BY CATEGORY</li>
    <li {% if categoryid is None %}class="active"{% endif %}><a href="{{documenturl}}{{querystring}}">All</a></li>
    {% for option in categorylist %}
    <li  {% if categoryid == option.0 %}class="active"{% endif %}><a href="{{documenturl}}{% addurlparameter querystring "categoryid" option.0|urlencode %}">{{option.1}}</a></li>
    {% endfor %}
  </ul>

  <br>
  {% setvar filterform.modifiedrange.cleanvalue as modified %}
  {% call_method listform "get_querystring" "modifiedrange" as querystring %}
  <ul class="nav nav-list">
    <li class="nav-header">BY MODIFIED</li>
    <li {% if modified is None %}class="active"{% endif %}><a href="{{documenturl}}{{querystring}}">All</a></li>
    {% for option in modifiedlist %}
    <li  {% if modified == option.0 %}class="active"{% endif %}><a href="{{documenturl}}{% addurlparameter querystring "modifiedrange" option.0|urlencode %}">{{option.1}}</a></li>
    {% endfor %}
  </ul>

  <br>
  {% setvar filterform.modifierid.cleanvalue as modifierid %}
  {% call_method listform "get_querystring" "modifierid" as querystring %}
  <ul class="nav nav-list">
    <li class="nav-header">BY MODIFIER</li>
    <li {% if modifierid is None %}class="active"{% endif %}><a href="{{documenturl}}{{querystring}}">All</a></li>
    {% for option in modifierlist %}
    <li  {% if modifierid == option.id %}class="active"{% endif %}><a href="{{documenturl}}{% addurlparameter querystring "modifierid" option.id|urlencode %}">{{option.username}}</a></li>
    {% endfor %}
  </ul>

</div>
{% endblock %}

templates/document/document_tagged_list.html
{% extends "../list.html" %}
{% load i18n %}

{% block breadcrumbs %}
<ul class="breadcrumb">
  <li><a href="{% url 'prescription:prescription_list' %}">{% trans 'Regional Overview' %}</a> <span class="divider">/</span></li>
  <li><a href="{% url 'prescription:prescription_home' prescription.id %}">{{prescription.burn_id}}</a> <span class="divider">/</span></li>
  <li><a href="">Document</a> <span class="divider">/</span></li>
  {% if tag %}
  <li>{{tag.name}}</li>
  {% endif %}
</ul>
{% endblock %}

{% block content_title %}
{{block.super}}
<h5><a class="btn btn-small btn-info" href=""><i class="icon-download-alt"></i> Download the Sign Inspection and Surveillance Form template</a>
    <div class="pull-right">
        <a class="btn btn-small btn-info" href="{% url 'document:prescription_taggeddocument_add' prescription.id tag.id %}?nexturl={{listform.fullpath}}">
            <i class="icon-plus icon-white"></i> Add document
        </a>
    </div>
</h5>

{% endblock %}